name: GdUnit4 Tests
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdunit4-action@v1
        with:
          godot-version: '4.4.1'
          godot-net: true
          project_dir: './src/'
          paths: 'res://test'
          console-verbosity: 'normal'
          timeout: '10'
          version: 'v5.0.3'